%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-autoware-system-msgs
Version:        1.10.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS autoware_system_msgs package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-autoware-common-msgs
Requires:       ros-humble-builtin-interfaces
Requires:       ros-humble-diagnostic-msgs
Requires:       ros-humble-geometry-msgs
Requires:       ros-humble-nav-msgs
Requires:       ros-humble-rosidl-default-runtime
Requires:       ros-humble-std-msgs
Requires:       ros-humble-unique-identifier-msgs
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-ament-cmake-auto
BuildRequires:  ros-humble-autoware-common-msgs
BuildRequires:  ros-humble-builtin-interfaces
BuildRequires:  ros-humble-diagnostic-msgs
BuildRequires:  ros-humble-geometry-msgs
BuildRequires:  ros-humble-nav-msgs
BuildRequires:  ros-humble-rosidl-default-generators
BuildRequires:  ros-humble-std-msgs
BuildRequires:  ros-humble-unique-identifier-msgs
BuildRequires:  ros-humble-ros-workspace
BuildRequires:  ros-humble-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-humble-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-humble-rosidl-interface-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-lint-auto
BuildRequires:  ros-humble-ament-lint-common
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-humble-rosidl-interface-packages(all)
%endif

%description
Autoware system messages package.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Mon Oct 20 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.10.0-1
- Autogenerated by Bloom

* Thu Jun 26 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.9.0-1
- Autogenerated by Bloom

* Wed May 21 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.8.0-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.7.0-1
- Autogenerated by Bloom

* Mon Apr 07 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.6.0-1
- Autogenerated by Bloom

* Mon Mar 31 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.4.0-1
- Autogenerated by Bloom

* Fri Dec 06 2024 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.3.0-1
- Autogenerated by Bloom

* Tue Oct 01 2024 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.2.0-1
- Autogenerated by Bloom

* Mon Jun 24 2024 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.1.0-1
- Autogenerated by Bloom

